### ISSUE TITLE
增加对易语言模块签名的支持

### ISSUE THREAD

**Issue by 66hh** [OpenEpl/EProjectFile#4]
[概述.txt](https://github.com/OpenEpl/EProjectFile/files/13348830/default.txt)
[易语言签名数据结构.txt](https://github.com/OpenEpl/EProjectFile/files/13348831/default.txt)
[VerifyESign.zip](https://github.com/OpenEpl/EProjectFile/files/13348835/VerifyESign.zip)
[易语言官方公钥.txt](https://github.com/OpenEpl/EProjectFile/files/13348841/default.txt)
[样例模块.zip](https://github.com/OpenEpl/EProjectFile/files/13348844/default.zip)

VerifyESign 易语言签名数据解析样例
易语言签名数据结构 签名数据结构
易语言官方公钥 易语言签名根秘钥
样例模块 带有签名的模块，可用易语言内置的"数字签名或验证"来验证签名，并且引用后模块名字中会显示(已签名)

**Comment by 66hh** [comment]
勘误:
易语言寻找签名数据的方法是
循环搜索0x27C31AFD并判断是否能搜索到当前这个0x27C31AFD前面的字节数+0x27C31AFD（也就是尾部数据）
这个签名数据是独立于ec模块格式的理论上给任何文件后面加上易语言都认（不过吴涛好像就只做了易包和易模块的签名,这个我之前做自签名工具的时候测试过了）

**Comment by ArcticLampyrid** [comment]
看起来签名区与原有的易工程结构无关，是个相当独立的东西
