### ISSUE TITLE
同步易语言模块加密处理

### ISSUE THREAD

**Issue by 66hh** [OpenEpl/EProjectFile#7]
易语言现在似乎已经完全废弃了0x00000001加密类型，就算填入0x00000001也会按0x00020001新加密处理，现在出现了一种干扰加密模块解析的手段，将0x00020001加密的模块标志改为0x00000001，易语言由于已经删除老加密全走新加密所以可以正常解密，而解析库还在使用老算法就导致了解析库无法正常解密

[样例.zip](https://github.com/user-attachments/files/17749804/default.zip)

**Comment by 66hh** [comment]
补充: 易语言现在似乎只是单纯把magic2字段当版本号判断是否大于当前版本了，理论上小于0x00020001的数字都可以？

**Comment by 66hh** [comment]
magic2似乎其实是版本号 分为两部分 主版本 0100 副版本 0000/0200 只要主版本不大于1 副版本不大于2易语言就可以接受 如果大于会提示又新版本易语言创建无法打开

**Comment by ArcticLampyrid** [comment]
> 易语言现在似乎已经完全废弃了0x00000001加密类型

`0x00000001` 主要是用于 *.e 工程文件（而非 *.ec 模块文件）的加密的

**Comment by 66hh** [comment]
> > 易语言现在似乎已经完全废弃了0x00000001加密类型
> 
> `0x00000001` 主要是用于 *.e 工程文件（而非 *.ec 模块文件）的加密的

原来如此，怪不得易语言忽略这个标志

**Comment by 66hh** [comment]
> > 易语言现在似乎已经完全废弃了0x00000001加密类型
> 
> `0x00000001` 主要是用于 *.e 工程文件（而非 *.ec 模块文件）的加密的

那能否增加一个参数来手动选择算法呢，或同步易语言的操作增加一个参数来指定是否是模块，magic2只作为版本来判断是否支持

**Comment by ArcticLampyrid** [comment]
本项目并不是以反编译为目的开发的，处理第三方混淆不是设计目的。
